# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeLight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeLight
  pod 'FirebaseStorage'
  pod 'FirebaseFirestore'
  pod 'FirebaseDatabase'
  pod 'FirebaseAuth'
  pod 'GoogleSignIn'
  pod 'IQKeyboardManager'

end
